---
title: "County Data on LWCF from TWS"
output:
  html_document:
    df_print: paged
---



```{r}
library(vroom)
library(dplyr)
library(tidyr)
library(stringr)
library(usmap)
library(tidycensus)
library(fixest)
library(kableExtra)
# ----
library(choroplethr)
library(choroplethrMaps)
library(usdata)
data(continental_us_states)
data(county.map)
# -----

# reading in TWS data 
myCounty <- vroom("creel_lwcf_tws.csv")

# Getting LWCF data ready for maps
myCounty <- myCounty %>%
  mutate(Name = str_to_title(Name)) %>%
  mutate(state.fips = fips(state = State))

# Getting map counties ready to merge in
county.map <- county.map %>%
  dplyr::select(STATE, NAME, region) %>%
  distinct()

# Merging so LWCF is mapable
myCounty <- left_join(myCounty, county.map, by = c("state.fips" = "STATE", "Name" = "NAME")) %>%
  filter(!is.na(region))






```

```{r}
#Maps

# Total projects ---------------
# Choosing which variable to map
myCounty <- myCounty %>%
  mutate(value = `Total Projects`)
county_choropleth(myCounty,
                 title = "Total Projects per County",
                 legend = "Projects") 

# Per Capital Spending ---------------
# Choosing which variable to map
myCounty <- myCounty %>%
  mutate(value = `Per Capita LWCF Spending`)
county_choropleth(myCounty,
                  title = "Per Capita LWCF Spending",
                  legend = "Dollars") 

# Total Spending ---------------
# Choosing which variable to map
myCounty <- myCounty %>%
  mutate(value = `Total LWCF Dollars`)
county_choropleth(myCounty,
                  title = "Total LWCF Spending",
                  legend = "Dollars") 






```


```{r}

# getting 0 back into the counties it dropped from
myCounty <- myCounty %>%
  mutate(region = as.character(region)) %>%
  mutate(region = if_else(nchar(region)==4, paste0('0', region), region))

census_api_key(key = 'b5fdd956635e498b0cc3288ebf9dfc802abbc93a', overwrite = TRUE, install = TRUE)
# readRenviron("~/.Renviron")
# Sys.getenv("CENSUS_API_KEY")

#Available variables in american community survey in the most recent year availabe
v18 <- load_variables(2018, "acs5", cache = TRUE)

#Getting income
medIncome <- "B19013_001" #Estimate!!Median income in the past 12 months --!!Total


#pulling data from census
theCensus <- tidycensus::get_acs(geography = "county", variables = medIncome, geometry = FALSE, cache_table = TRUE)

theCensus <- theCensus %>%
  dplyr::select(GEOID, estimate)

# merging in income 
myCounty <- left_join(myCounty, theCensus, by = c("region" = "GEOID"))


#renaming variable 
myCounty <- myCounty %>%
  rename(total_spending = `Total LWCF Dollars`) %>%
  rename(total_projects = `Total Projects`) %>%
  rename(per_cap_spending = `Per Capita LWCF Spending`) %>%
  rename(median_income = estimate)

```


```{r}

total_spend.reg <- feols(data = myCounty, total_spending ~ median_income | State)
per_cap.reg <- feols(data = myCounty, per_cap_spending ~ median_income | State)
projects.reg <- feols(data = myCounty, total_projects ~ median_income | State)



etable(total_spend.reg, 
       per_cap.reg, 
       projects.reg,
       signifCode = c("***"=0.01, "**"=0.05, "*"=0.10)) %>%
    kbl(caption = "Influence of income on LWCF investment", 
        col.names = c("Total LWCF Dollars", "Total Projects", "Per Capita LWCF Spending")) %>%
    kable_classic_2(full_width = F) %>%
    add_footnote(" ***=0.01, **=0.05, *=0.10")
```